# These are the development environment configuration values
spring.profiles: dev

swagger:
   domain: localhost
   port: 8080
   
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# Cassandra database configuration
cassandra:
   host: localhost
   port: 9042
   
