[[domain-objects]]
= Domain Objects 
:sectnums:
:icons: font
    	  	
Henge relies on a number of domain objects to encapsulate the data needed to provide its property configuration service. Each domain object has a Java class inside the application code, and a JSON representation for REST calls. Most of the domain objects have a name and version attribute associated with them, and are immutable. All update methods applied to the immutable objects will create a new entry in the repository. 

== Property

A `Property` is a configuration variable. It has the following attributes:

* *name*: the name of the property.
* *description*: the description of the property.
* *defaultValue*: the default value of the property when no `Scope` is defined.
* *propertyScopedValues*: a set of alternative values for the property, one for each `Scope`.

Properties are not referenced directly in JSON format. Instead, several properties are defined inside a `PropertyGroup`. See `PropertyGroup` below for a JSON example of how properties are defined.

[[Scope]]
== Scope

A `Scope` is a key-value pair used to specify different values for properties in a given scenario. A `Scope` is useful when a configuration variable has different values depending on the environment the application is run in. For example, you could have a scope key as *env* and possible values of *dev*, *test*, and *prod* which are particular environments the application runs in. This would define three instances of `Scope` that can be used to set different values for the properties in those environments. 

See the <<domain_reference#PropertyGroup, Property Group>> section below for an examples of using scopes and assigning values to them. 

[[PropertyGroup]]
== PropertyGroup

A `PropertyGroup` groups properties that belong to the same context and go together. It has the following attributes: 

* *name*
* *version*
* *createdBy*
* *createdDate*
* *description*
* *type*: the type of the `PropertyGroup`. It can be one of two values: *APP* or *LIB*. *APP* should be used for your application, and *LIB* for properties that belong to some library or dependency of your project. This distinction is also used when evaluating property values. If the same `Property` name exists in both an *APP* and *LIB* `PropertyGroup` (there is a name conflict), *APP* type properties override *LIB* properties.
* *isActive*: true indicates the `PropertyGroup` is active.
* *properties*: the set of `Properties` the `PropertyGroup` contains.

An example of a `PropertyGroup` might be a configuration for a database connection. For this `PropertyGroup` you need `Property` values for *host* and  *port*. Let's assume you have *dev*, *test* and *prod* environments where the *host* values for these properties may be different, though the *port* is the same. You would define a `PropertyGroup` with two properties, where the *host* property has three `propertyScopedValues` and a `defaultValue`. The following is a JSON representation of this example:

[source]
----
{
	"name": "dbconfig",
	"version": "1.0.0",
	"description": "Example database configuration",
	"type": "APP",
	"active": true,
	"properties": [{
		"name": "dbhost",
		"description": "Ip of database host",
		"defaultValue": "localhost", # //<3>
        "propertyScopedValues": [{
			"key": "env=dev", # //<1>
			"value": "127.0.0.1" # //<2>
		}, {
			"key": "env=test",
			"value": "192.168.0.10"
		}, {
			"key": "env=production",
			"value": "192.168.0.20"
		}]
	}, {
		"name": "dbport",
		"description": "Port of database",
		"defaultValue": "4321" # //<4>
	}
	}]
}
----  
<1> The key of the `propertyScopedValue` is a `Scope` whose key is *env* and value is *dev*.
<2> *127.0.0.1* is the value of the *dbhost* property when the `Scope` is *env=dev*.
<3> The *dbhost* property uses the `defaultValue` of *localhost* if no `Scope` is specified when the search is performed on Henge.  
<4> For *dbport*, there are no `propertyScopedValues` and only a `defaultValue` because the *dbport* is the same for all environments. 

The previous example shows a single scoping of different values based on dev, test and prod environments. But how are more complex environments using multiple scopes set up? For more on setting up `PropertyGroups` within complex environments, see  <<scope_hierarchy#scopes, Using Scope Sets and the Scope Hierarchy>>.  

== FileVersion

Henge can also be used to store configuration files that cannot be translated to a *.properties* file. For example, let's assume that some part of your application needs to store a long list of geolocations that are fixed, but could change between instances of the system. Being a long list, you would probably not want to store it as property values. It would be more appropriate to store the geolocations in a text file. Henge stores files like these in an entity called `FileVersion`, which has the following attributes: 

* *name* 
* *version*
* *description*
* *content*: a byte array containing the contents of the file.
* *fileName*: the source file name. 
* *createdBy*
* *createdDate*
* *modifiedBy*
* *modifiedDate*

Here is an example of `FileVersion` in JSON format: 
[source]
----
{
  "name": "GeoLoc",
  "version": "1.0.0",
  "description": "List of GeoLocations of Mountains",
  "content": "TW91bnQgRWxiZXJ0LCBDb2xvcmFkb3wzOS4xMTc4NTEyfC0xMDYuNDQ1MTU5OQpNb3
  VudCBNaXRjaGVsbCwgTm9ydGggQ2Fyb2xpbmF8MzUuNzY0OTYxMnwtODIuMjY1MTEKTW91bnQgUmFp
  bmllciwgV2FzaGluZ3Rvbnw0Ni44NTI5MTI5fC0xMjEuNzYwNDQ0Ng==",
  "filename": "GeoLoc.txt",
  "createdBy": "rdaugherty",
  "createdDate": "2016-08-22T09:44:51.58",
  "modifiedBy": "rdaugherty",
  "modifiedDate": "2016-08-22T09:44:51.58"
}
----
== VersionSet

A `VersionSet` groups specific versions of `PropertyGroups` and `FileVersions`, wrapping up all the properties needed for a given application. 

NOTE: Here ‘application’ typically represents a more granular piece of a system such as a microservice or smaller application that the `VersionSet` provides properties for.   

The `VersionSet` itself has a version number associated with it. The reasoning behind this is that applications using Henge are versioned and the corresponding configuration must be able to keep up with the application's evolution, having different versions that can coexist and attend to multiple releases of the application it serves.  

When a `VersionSet` is returned by a query to Henge, it is processed and all the properties contained in its `PropertyGroups` are evaluated considering the 
`Scopes` given in the query. A *.properties* file is then generated and sent back to the client. 

`VersionSets` have the following attributes:

* *name* 
* *version*
* *createdBy*
* *createdDate*
* *description*
* *propertyGroupReferences*: a set of references to `PropertyGroups`. A reference contains only *name* and *version*, which are sufficient to identify a `PropertyGroup`.
* *fileVersionReference*: a set of references to `FileVersions` (similar to above). 

Here is an example of a `VersionSet` in JSON format:

[source]
----
{
	"name": "ExampleVersionSet",
	"version": "1.0.0",
	"description": "Example of a VersionSet",
	"fileVersionReferences": [{
		"name": "configfile",
		"version": "1.0.0"
	}],
	"propertyGroupReferences": [{
		"name": "dbconfig",
		"version": "1.0.0"
	}, {
		"name": "some-other-property-group",
		"version": "latest" # //<1>
	}]
}
---- 
<1> A `VersionSet` can point to a symbolic version (latest), in which case it will always point to the highest version number for that `PropertyGroup`. 

[[Mapping]]
== Mapping

After creating `PropertyGroups` and `VersionSets`, the configuration properties defined in them are not yet available to clients. They only become live after creating a `Mapping` entry, which maps a query for a given set of scopes to a specific version set.

A `Mapping` entry is created with REST parameters that include an *application*, a *scopeString* that defines the set of scopes, and a *body* that indicates the name and version of the `VersionSet`. 

For instance, you could create a `Mapping` with this URL request indicating the application and scopes:  

[source]
----
http://localhost:8080/henge/v1/mapping?application=loginApp&scopeString=env=prod,stack=financeWebStack
----

And this body indicating the `VersionSet`: 

[source]
----
{
  "name": "VersionSet-1",
  "version": "1.0.0" //<1>
}
----
<1> The version could also be specified as "latest", in which case it will always point to the highest version number for that `VersionSet`. 

The `Mapping` is stored as a mutable JSON object where the *application* itself is a scope, as shown: 

[source]
----

{
  "{\"scopeSet\":[{\"key\":\"env\",\"value\":\"prod\"},{\"key\":\"stack\",\"value\":\"financeWebStack\"},{\"key\":\"application\",\"value\":\"loginApp\"}]}" : {
    "name" : "VersionSet-1",
    "version" : "1.0.0"
  }
}
----

Using the `search` endpoint, a complete set of properties is retrieved from Henge by providing an *application* and a *set of scopes*. The `Mapping` is looked up to provide the specific `VersionSet`, which is then converted to a *.properties* file. 

For instance, if the above `Mapping` was in place, you could then retrieve a complete set of properties using the following `search` call: 

[source, url]
----
http://localhost:8080/henge/v1/search/loginApp?scopes=env=prod,stack=financeWebStack
----
