= Henge User's Guide
Kenzan <support_henge@kenzan.com>
v0.9.0, October 7, 2016
:toc: left
:toclevels: 3
:toc-title: Henge User's Guide
:sectnums:
:icons: font

A henge is a Neolithic structure consisting of an earthen bank and ditch encircling a flat area. Like the famous example of Stonehenge, henges might contain a ritual structure such as a circle of timbers or standing stones, and they could be accessed by walking along a processional avenue.

Henges were important places where people from the surrounding area gathered to share ideas and beliefs. Similarly, the Henge project provides an avenue to a central place where applications can go at runtime to receive values for properties, or to set values which can be used by other applications. In this way, Henge acts as a service for properties, and it provides a mechanism for the dynamic exchange of values—much like henges did long ago.

TIP: If you have questions about Henge, or how to integrate a dynamic properties service into your application architecture, feel free to drop us a line at support_henge@kenzan.com.

include::henge_overview.adoc[leveloffset=+1]

include::getting_started.adoc[leveloffset=+1]

include::alternate_deploy.adoc[leveloffset=+1]

include::hello_properties.adoc[leveloffset=+1]

include::use_case_simple_app.adoc[leveloffset=+1]

include::use_case_complex_app.adoc[leveloffset=+1]

include::domain_reference.adoc[leveloffset=+1]

include::profiles_reference.adoc[leveloffset=+1]

include::metrics_reference.adoc[leveloffset=+1]

include::repository_reference.adoc[leveloffset=+1]

include::service_reference.adoc[leveloffset=+1]
