version: '2'
services:
  grafana:
    build: ../grafana/
    ports:
      - "3000:3000"
    links:
      - influxdb
  influxdb:
    image: influxdbgrafana_influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./influxdb_data:/data
